version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.8.0.232.b09-3.6.2-b3291

commands:
  dockerhub-login:
    description: "Connect to DockerHub"
    steps:
      - run:
          name: Login to DockerHub
          command: |
            docker login -u ${DOCKERHUB_LOGIN} -p ${DOCKERHUB_PASS}

jobs:
  build:
    executor: build-executor
    steps:
      - checkout
      - restore_cache:
          key: oca-github-plugin-{{ checksum "pom.xml" }}
      - run: mvn validate
      - run: mvn dependency:go-offline
      - run: mvn clean package -DskipTests=true
      - run: mvn verify -DskipTests=false
      - save_cache:
          paths:
            - ~/.m2
          key: oca-github-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Collect Artifacts
          command: |
            mkdir -p /tmp/artifacts;
            cp target/*.war /tmp/artifacts
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: ~/project
          paths:
            - target

  oci-build:
    executor: build-executor
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/project
      - dockerhub-login
      - run:
          name: Build Docker OCI file
          command: |
            cd docker
            ./build.sh
      - store_artifacts:
          path: docker/images/container.oci
      - persist_to_workspace:
            root: ~/project
            paths:
              - docker/images/container.oci

  oci-publish:
    executor: build-executor
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/project
      - dockerhub-login
      - run:
          name: Load Docker image
          command: |
            docker image load -i docker/images/container.oci
      - run:
          name: Tag and push container images
          command: |
            cd docker
            ./tag-n-push.sh
  oci-deploy:
    executor: build-executor


workflows:
  build-package:
    jobs:
      - build
      - oci-build:
          requires:
            - build
      - oci-publish:
          requires:
            - oci-build
          filters:
            branches:
              only:
                - master
                - migrate/circleci

