version: 2
jobs:
  build:

    working_directory: ~/oca-github-plugin

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: oca-github-plugin-{{ checksum "pom.xml" }}

      - run: mvn validate

      - run: mvn dependency:go-offline

      - run: mvn clean package -DskipTests=true

      - run: mvn verify -DskipTests=false

      - save_cache:
          paths:
            - ~/.m2
          key: oca-github-plugin-{{ checksum "pom.xml" }}

      - run:
          name: Collect Artifacts
          command: |
            mkdir -p /tmp/artifacts;
            cp target/*.war /tmp/artifacts

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: /tmp/artifacts
