version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.8.0.232.b09-3.6.2-b3291

jobs:
  build:
    executor: build-executor
    steps:
      - checkout

workflows:
  build-package:
    jobs:
      - build

